---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: >
      sh -c "../upgrade.sh && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ../netbox_devicetype_importer:/source/netbox_devicetype_importer
    tty: true
  worker:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: sh -c "python manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes: 
      - ../netbox_devicetype_importer:/source/netbox_devicetype_importer
    tty: true
  postgres:
    image: postgres:12
    env_file: dev.env
    volumes:
      - pgdata_netbox_devicetype_importer:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_netbox_devicetype_importer:
