ARG python_ver=3.7
FROM python:${python_ver}

ARG netbox_ver=master
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt

RUN pip install --upgrade pip

# -------------------------------------------------------------------------------------
# Install NetBox
# -------------------------------------------------------------------------------------
#RUN git clone --single-branch --branch ${netbox_ver} https://github.com/netbox-community/netbox.git /opt/netbox/ && \
#    cd /opt/netbox/ && \
#    pip install -r /opt/netbox/requirements.txt

RUN curl -SL https://github.com/netbox-community/netbox/archive/refs/tags/v3.0.0.tar.gz  --output download.tar.gz && \
    tar -xzf download.tar.gz -C /opt && \
    mv /opt/netbox-3.0.0 /opt/netbox && \
    pip install importlib-metadata==4.13.0 rq==1.13.0 && \
    pip install -r /opt/netbox/requirements.txt

COPY ./develop/configuration.py /opt/netbox/netbox/netbox


# Work around https://github.com/rq/django-rq/issues/421 
RUN pip install django-rq==2.3.2

# -------------------------------------------------------------------------------------
# Install Netbox Plugin
# -------------------------------------------------------------------------------------
RUN mkdir -p /source
WORKDIR /source
COPY . /source

#RUN pip install -r requirements.txt
RUN python setup.py develop

WORKDIR /opt/netbox/netbox/
